### ISSUE TITLE
Top-level issue to track game I/O protection dongles

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1339]
Related issues:
- [x] #1153 - SDS's Speedstar compiler
- [x] #1198 - Cortechs Corp's CodeWriter
- [x] #1247 - Robocom Ltd's RoboCAD
- [x] #1312 - Hayden's Applesoft compiler

False-positive (not a protection dongle):
- [x] #1317 - Quark's WordJuggler (for shift/control key mods)

**Comment by tomcw** [comment]
Closing this top-level issue, since all _known_ protection dongles now exist in AppleWin.
