### ISSUE TITLE
AppleWin in Wine and CPU usage.

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#399]
Hi,

I recently monitored the CPU utilisation of AppleWin when it runs in Wine and noticed a sharp increase.

Version 1.25.0.4 runs at around 5% while current master is at 25%.

Bisection is very noisy and I could not find anything clear, but by putting some timers in the code I noticed for instance that inside ContinueExecution()

- CpuExecute(..., true)   takes 10% of running time and CPU alone
- The other 10% comes from VideoRefreshScreen()

Maybe I can single one a call Wine implements badly and maybe they can sort it out like they did with the multimedia timers a year or so ago.

I noticed there is a lot of NTSC related code in the new version, and before continuing I wonder if there is something new or that has recently change which is worth look at first.

Regards

**Comment by tomcw** [comment]
Hi,

Thanks for trying & reporting your Wine experience. This is always an interesting data-point.

Compared to 1.25, AppleWin 1.26 (as you noticed) has lots of new NTSC related code. This does cycle accurate video rendering (ie. for each emulated 6502 opcode, it will update 2-7 cycles of video data) and as such there is a larger amount of CPU utilisation.

The latest [experimental build](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.1) has some optimisations but overall we are unlikely to get back to 1.25's low CPU usage (unless we eg. offload to GPU).

**Comment by audetto** [comment]
I do notice indeed a much more realistic emulation of TV colors.
I've always used an Apple IIe with a green monochrome monitor, so I had never appreciated how was the real tv output.

When I tested, I did take the code from master which I believe is very similar to 1.26.2.1 to which you pointed me. Due to the CPU usage in window (almost 0%), I still believe this is due to some suboptimal wine calls. Normally pure userspace code is emulated at zero cost. Will try to dig deeper.

Probably it goes well beyond the scope of this issue, but it would be interesting to know more details of the TV emulation implemented now. Being called NTSC, does it imply a potential PAL version?

Naively one could think that every x cycles, the memory storing the text/hires graphics is copied/converted to the emulator screen (a bit like some game engines, with update() and draw()), but this must be way off what really happens.

What would you offload to the GPU? In the end you need pixel by pixel conversion (... I fell I am totally wrong again here ...). How can the GPU help?

Anyway, it is all very interesting.

**Comment by sicklittlemonkey** [comment]
> we are unlikely to get back to 1.25's low CPU usage (unless we eg.
offload to GPU).

It is a pity that non-NTSC modes suffer the same loss of performance.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
On 30 March 2017 at 10:15, Andrea <notifications@github.com> wrote:
> When I tested, I did take the code from master which I believe is very
similar to 1.26.2.1 to which you pointed me. Due to the CPU usage in window
(almost 0%), I still believe this is due to some suboptimal wine calls.
Normally pure userspace code is emulated at zero cost. Will try to dig
deeper.

I'll try to get you some performance metrics from Windows 10 to compare.
First I'll need to try to fix the profiler I use ... some of the results
have been strange recently.

But I can say:
- When the enhanced //e emulator is running at 1 Mhz: (or 2 etc, but not
max speed)
  - Inside CpuExecute, 99.8% of the time is spent in Cpu65C02.
  - Inside Cpu65C02, 98+% of the time is spent in VideoUpdateCycles.
  - Inside VideoUpdateCycles, 96%+ of the time will be spent in something
like updateScreenSingleHires etc.
  - Inside updateScreenSingleHires (etc), 92%+ of the time will be spent
in updatePixelHueColorTVDoubleScanline.
  - updatePixelHueColorTVDoubleScanline spends all time in itself - this is
where most of the NTSC emulation work is done.

- When the enhanced //e emulator is running at max speed:
  - Inside CpuExecute, 99.8% of the time is spent in Cpu65C02.
  - Inside Cpu65C02 the time will be mostly spent doing disk IO,
Mockingboard, time in VideoGetVblBar, other IO, reading the joystick,
checking the mouse, speaker access etc.
  - Relatively little time is spent in the NTSC rendering - as Tom says
this has already been optimized - otherwise max speed was not very fast.

> What would you offload to the GPU? In the end you need pixel by pixel
conversion (... I fell I am totally wrong again here ...). How can the GPU
help?

OpenEmulator (for the Mac) has NTSC emulation implemented on the GPU. It's
fantastic.

Cheers,
Nick.

**Comment by tomcw** [comment]
@audetto 
>Being called NTSC, does it imply a potential PAL version?

Yes, I don't see why not... but the feedback has been more about providing a simplified screen mode, #357.

>Naively one could think that every x cycles, the memory storing the text/hires graphics is copied/converted to the emulator screen [...]

Every 6502 opcode (2-7 cycles) the Apple II memory is copied and rendered into a Windows display buffer. It must be done every opcode, as each opcode could potentially change Apple II video mode or Apple II video memory.

**Comment by tomcw** [comment]
>- When the enhanced //e emulator is running at max speed:
> : 
> - Relatively little time is spent in the NTSC rendering - as Tom says
this has already been optimized - otherwise max speed was not very fast.

Right: max speed skips the per-opcode NTSC video rendering. Instead it will _periodically_ redraw the whole Apple II screen (ie. every ~17ms of **real** PC time, but only if there's been a change to the current Apple II video memory).

**Comment by Michaelangel007** [comment]
@audetto

Just to clarify WHY the NTSC rendering changes happened.  There were 2 goals:

* Accurate colors
* Proper video mode switching

On a real Apple you can switch video modes **mid-scanline** -- now most programs _don't_ do this -- but a few demos do.  In order for us to properly 100% simulate a real Apple we chose to err on the side of correctness.  Sadly, the trade-off is that we took a pretty big performance hit as you've noticed. :-/

I'm currently using both Applewin versions 25 and 26 depending on what I need. v25 for speed, v26 for colors.

We still have a few misc. performance optimizations left but again this involves some major re-writes which entails making it doesn't break which is why I've been punting on it.  It will be a while before I circle around to optimize some of the virtual calls away -- currently busy with reverse engineering and game dev Apple projects.

@AppleWin/dev did you guys want my NTSC optimization notes?

**Comment by tomcw** [comment]
> did you guys want my NTSC optimization notes?

Yes please! :)

@audetto: why is low CPU utilisation important to you? (either under Wine or not)

**Comment by Michaelangel007** [comment]
At one point I was going to post this to c.e.a2 ... but SQUIRREL.  Anyways, here are some notes from back in Jan 2015 ... IIRC most (all?) of these have been incorporated into the NTSC rendering when I cached the video mode changes byte video byte -- but it wouldn't hurt to double-check.

Enjoy! 

```
 - - - 8< - - -
```

By using DOD (Data-Orientated Design) I've managed to get a massive speed increase 2x - 4x with the NTSC rendering code via manually function unrolling. This is proof of the "Flexible & Slow" VS "Rigid & Fast" axiom.

In C++ terminology this is equivalent to "flattening virtual calls". Whoa! What is this talk about Virtual Calls? I thought Sheldon's code was all C -- he doesn't have virtual calls!? True, he doesn't have virtual function call, however, _effectively_ there are 14 function calls PER video byte! Compilers can't optimize a pointer-to-pointer-function call away.

|Calls| Function                       |
|:---:|:------------------------------:|
| x1  | wsVideoUpdate                  |
| x2  | monochrome vs chromatic branch |
| x14 | pixels                         |

This is -why- the new NTSC rendering code so slow compared to previous emulators.

**TL:DR;** Compilers can't optimize double indirection, use DOD to manual unroll.

This is an introduction to a 4 Part "whitepaper" on how Sheldon's NTSC rendering works:

# Table of Contents

  Part 0 - Legend
  Part 1 - Function call tracing
  Part 2 - Optimizing
  Part 3 - 64K lookup table

Optimzing NTSC Rendering - Part 0 - Legend
==========================================

First, some abbreviations since the original function names
are little misleading.  Any time you read:

 * SinglePixel
 * DoublePixel

There are refering to _scanline blendings_, NOT pixels.
All of these actually draw *one* pixel to *two* scanlines.

The single/double refers to the type of RGB blending.

I use the terms:

```C
  half =  25%  code: mp = ((*cp & 0x00fcfcfc) >> 2)
  full = 100%  code: *mp = *cp

  half    color1 = ((color0 & 0x00fcfcfc) >> 2)
  quarter color1 = color0 - ((color2 & 0x00fcfcfc) >> 2
```

to distinguish the types of blending:

This table describes the type of scanline blending for

* Primary Scanline Brightness %, and
* Secondary Scanline Brightness %.

```
  Mode     Original Name  Description
  =========================================================
  Mon1     SINGLEPIXEL    half    100%,  25%
  Mon2     DOUBLEPIXEL    fulll   100%, 100%
  Hue1     SINGLETVPIXEL  quarter 100%,  75%
  Hue2     DOUBLETVPIXEL  fulll   100%, 100%
```

Note: Sheldon's original code has some stale code left in SINGLETVPIXEL:

```C
   prevlin = (unsigned int *)(vbp0 + 8 * FRAMEBUFFER_W); \
   prevp = *prevlin; \
```


Another problem is that unsigned, unsigned int, or long was used clouding if 16-bits or 32-bits of precision are needed. AppleWin uses the standard (stdint.h) `uint16_t` and `uint32_t` for clarity, but I digress.

```
Legend / Definitions:

  Mode     Original Name          Description
  ================================================================
  TEXT40   wsUpdateVideoText      40-col text mode
  TEXT80   wsUpdateVideoDblText   80-col text mode
  GR40     wsUpdateVideoLores     Lo-Res
  DGR40    wsUpdateVideo7MLores   Double Lo-Res w/o 80-col active
  DGR80    wsUpdateVideoDblLores  Double Lo-Res w/  80-col active
  HGR40    wsUpdateVideoHires     Hi-Res
  DHGR40   wsUpdateVideoHires0    Double Hi-Res w/o 80-col active
  DHGR80   wsUpdateVideoDblHires  Double Hi-Res w/  80-col active

           VIDEO_DRAW_BITS        'bt' is 14-bit composite signal

  B&WMon1  ntscMonoSinglePixel    Black & White Monitor: half
  B&WMon2  ntscMonoDoublePixel    Black & White Monitor: copy
  B&WTV1   ntscMonoTVSinglePixel  Black & White ColorTV: quarter
  B&WTV2   ntscMonoTVDoublePixel  Black & White ColorTV: full
  HueMon1  ntscColorSinglePixel   Chromatic     Monitor: half
  HueMon2  ntscColorDoublePixel   Chromatic     Monitor: full
  HueTV1   ntscColorTVSinglePixel Chromatic     ColorTV: quarter
  HueTV2   ntscColorTVDoublePixel Chromatic     ColorTV: mix
```

Here are the tentative cleaned up names in AppleWin 1.26

```
  Mode     Original Name                  Description
  ================================================================
  TEXT40   updateScreenText40             40-col text mode
  TEXT80   updateScreenText80             80-col text mode
  GR40     updateScreenSingleLores40      Lo-Res
  DGR40    updateScreenDoubleLores40      Double Lo-Res w/  80-col active
  DGR80    updateScreenDoubleLores80      Double Lo-Res w/o 80-col active
  HGR40    updateScreenSingleHires40      Hi-Res
  DHGR40   updateScreenDoubleHires40      Double Hi-Res w/  80-col active
  DHGR80   updateScreenDoubleHires80      Double Hi-Res w/o 80-col active

           updatePixels                   bits is 14-bit composite signal

  B&WMon1  PixelBnWMonitorSingleScanline  Black & White Monitor mode: half
  B&WMon1  PixelBnWMonitorDoubleScanline  Black & White Monitor mode: full
  B&WTV1   PixelBnWColorTVSingleScanline  Black & White ColorTV mode: quarter
  B&WTV2   PixelBnWColorTVDoubleScanline  Black & White ColorTV mode: full
  HueMon1  PixelHueMonitorSingleScanline  Chromatic     Monitor mode: half
  HueMon2  PixelHueMonitorDoubleScanline  Chromatic     Monitor mode: full
  HueTV1   PixelHueColorTVSingleScanline  Chromatic     ColorTV mode: quarter
  HueTV2   PixelHueColorTVDoubleScanline  Chromatic     ColorTV mode: full


                                             Primary Scanline Brightness %
                                                    Secondary Scanline Brightness %
  Mon1     FramebufferMonitorSingleScanline  100%,  25%
  Mon2     FramebufferMonitorDoubleScanline  100%, 100%
  Hue1     FramebufferColorTVSingleScanline  100%,  75%
  Hue2     FramebufferColorTVDoubleScanline  100%, 100%
```

Optimzing NTSC Rendering - Part 1 - Function call tracing
=========================================================

Let's trace what happens on a 6502 clock cycle

    Update Screen( # clock cycyles ) <-- first virtual function
       get 14 composite bits
          Update Pixels on 2 scanlines <-- second virtual function

Effectively there are 2 two "Virtual Functions" calls here:

   Update Screen:  wsVideoUpdate  (and corresponding wsVideoText  )
   Draw Bits    :  if color burst on, choose between monochrome or color
   Update Pixel :  ntscColorPixel (and corresponding ntscMonoPixel)

Now the first one we can't do much about, but what about inlining the second one?
Can we get rid of it?

To answer that let's take a look at the Video Mode vs Time callstack diagram:
(The video mode is across the X axis, time is across the Y axis)

```
+--------+--------+------+------+------+-------+--------+-------+ Set : SetVideoMode( $C05x )
| TEXT40 | TEXT80 | GR40 | GR80 | GR81 | HGR40 | DHGR80 | DHGR40| Draw: updateScreenX( cycles_6502 )
+--------+--------+------+------+------+-------+--------+-------+ 
 \                                                             /
  \                                                           /
   \                                                         /
    \                                                       /
     \                                                     /
      \                                                   /
       +-------------------------------------------------+
       |                                                 | 
       |        For 14 pixels on the scanline            | 
       |Draw: VIDEO_DRAW_BITS(bt)  updatePixels(bits_14) | 
       +-------------------------------------------------+
      /                         |                         \
     /                          |                          \
    /  Black and White          |  Chromatic Hues           \
   /      ntscMonoPixel()       |     ntscColorPixel()       \
  /       g_pFuncUpdateBnWPixel |     g_pFuncUpdateHuePixel   \
 /                              |                              \
+-------+--------+------+-------|--------+--------+------+------+
|B&WMon1|B&WMon2 |B&WTV1|B&WTV2 |Monitor1|Monitor2|Color1|Color2| Set: wsVideoStyle
+-------+--------+------+-------|--------+--------+------+------+ Draw: ntsc{Mono,Color}{Single,Double}Pixel
| Mon1  | Mon2   | Hue1 | Hue2  | Mon1   | Mon2   | Hue1 | Hue 2| 
+-------+--------+------+-------|--------+--------+------+------+ 
```

Optimzing NTSC Rendering - Part 2 - Optimizations
=================================================

So how do we get our speed back?

First by analyzing the permutations:

    Video Mode  : TEXT40 / TEXT80 / GR40 / GR80 / DGR40 / HGR40 / DHGR80 / DHGR40
    Color       : Yes / No
    Display Type: Standard / TV

Since there are 3 axis we would normally need a 3D matrix.
However, we can collapse this 3D matrix down into a more readable 2D format:

```
Hue\Mode| TEXT40 | TEXT80 | GR40 | GR80 | GR81 | HGR40 | DHGR80 | DHGR40|
========+================================================================
B&WMon1 | 
B&WMon1 |
B&WTV1  |
B&WTV2  |
HueMon1 |
HueMon2 |
HueTV1  |
HueTV2  | 
```

When the user presses F9 you stay in the same column.
When a 6502 program sets video mode, you stay in the same row.

Let's say we want to optimize the HGR40 mode for Color Monitors with 100% double scanline.

Our function name is simply the Y+X names concatenated to provide an _unique_ name.

Here is an annotated example of the inner loop for: UpdateHGR40HueMon2()

```C
    //
        uint8_t *pMain = MemGetMainPtr(addr);
        uint8_t  m     = pMain[0];
        uint16_t bits  = g_aPixelDoubleMaskHGR[m & 0x7F]; // Optimization: hgrbits second 128 entries are mirror of first 128
        if (m & 0x80)
        bits = (bits << 1) | g_nLastColumnPixelNTSC;

    // Optimization #1
    // Since we KNOW the colorBurst is on
    // We don't need to waste try trying to determine if we should call
    // the monochrome or chromatic version

    // Optimization #2
    // This if( colorBurst ) switch poiNTSCColorTVnter-to-function
    // forces us to recalculate the frame buffer pointer for:
    //   a) this scanline
    //   b) the  previous scanline
    // We calculate it one 

        uint32_t  c;
        uint32_t *p = (uint32_t*)g_pVideoAddress;

    // For Mon2 only need 1 previous scanline
        uint32_t *q = p - 1*FRAMEBUFFER_W;

        g_nLastColumnPixelNTSC = (bits >> 13) & 1;
        for( int i = 0; i < 14; i++ )
        {
            g_nSignalBitsNTSC = ((g_nSignalBitsNTSC << 1) | (bits & 1)) & 0xFFF;
    // Optimization #3
    // Instead of wasting time trying to determine which table to use
    //   NTSCMono
    //   NTSCColor
    //   NTSCMonoTV
    //   NTSCColorTV
    // We already KNOW which table we'll use
        c = *((uint32_t*)&g_aHueMonitor[g_nColorPhaseNTSC][g_nSignalBitsNTSC]);

        *p = *q = c;
        bits >>= 1;

    // Optimization #4
    // There is a nextPhase table
    //   static int nextPhase[] = {1,2,3,0};
    // But this isn't needed
        ++g_nColorPhaseNTSC &= 3;

    // re-use pointer to scanlines
            p++;
            q++;
            g_pVideoAddress++;
        }
```

Optimzing NTSC Rendering - Part 3 - 64K lookup table
====================================================

Building of the 64K RGB table:

The Apple has a master clock of exactly 14,318,180 Hz,
commonaly abbreviated 14 MHz.
An Apple generats a composite chroma signal at exactly: 3,579,545 Mhz.
This is usually abbreviated 3.5 Mhz.

14 Mhz/3.5 Mhz = exactly 4 phases.

When we switch one pixel column we cycle through 1 of these 4 phases.

 = 4 phases * 4096 colors * 32-bits (alpha isn't used)
 = 64K


# TODO

* [ ] Figure out how the heck `initChromaPhaseTables()` works!
  * [ ] Is it a ButterworthLowPass2 filter???
  * [ ] What are the params???
* [ ] `initFilterChroma()`
* [ ] `initFilterLuma0()`
* [ ] `initFilterLuma1()`
* [ ] `initFilterSignal()`

**Comment by Michaelangel007** [comment]
> @audetto: why is low CPU utilisation important to you? (either under Wine or not)

Tom, I know you asked audetto but let me chime in here:

* Lower CPU % = more battery life on laptops ,
* Allows for running multiple copies of the emulator,
* Faster "full speed" emulation for externally controlled apps -- think of an AI that interfaces with AppleWin to "play a game"

I don't know the details of _what_ audetto's use case is -- but it IS important.  Regardless AppleWin's CPU % has become more expensive -- which has a negative user experience. :-/

**Comment by Michaelangel007** [comment]
> (unless we eg. offload to GPU).

We would basically need the GPU to render ALL the video modes simultaneously, and then use a stencil-like-operation to "stitch" them together.

**Comment by audetto** [comment]
Back to the request of CPU usage.
I use it in wine so CPU utilisation is normally higher that what it is in Windows anyway.
At the moment is 25%.

In windows it is much less, I only have a Virtual Box and I cannot even measure it: ~1%.

As it happened in the past already (re timer), it seems AppleWin uses some windows calls that are not emulated efficiently in wine and from 25% to 100% the distance is not much.

I am just back from holidays and I have a lot to read here, and then I will try to identify which calls is expensive.

Since I only ever used an Apple IIe with a monochrome green monitor (I did not even know I could attach it to a TV...), does the whole NTSC apply in the real case to a monitor as well?

**Comment by Michaelangel007** [comment]
> Since I only ever used an Apple IIe with a monochrome green monitor (I did not even know I could attach it to a TV...), does the whole NTSC apply in the real case to a monitor as well?

Yes, both color and monochrome.

You can seen pictures of real hardware in bug #254

**Comment by audetto** [comment]
I did a quick comparison and I got this

In Win10 (in VBox)

ContinueExecution (except the wait SysClk_WaitTimer) 1.1%
StretchBlt in VideoRefreshScreen 0.5%  (so roughly half of the total)

In wine

ContinueExecution (except the wait SysClk_WaitTimer) 22%
StretchBlt in VideoRefreshScreen 11%  (so again half of the total)

The % are time in the section / total wall clock (so basically the CPU usage) (average over the last 2 seconds).
This is after booting DOS and waiting 10 seconds.
The rest of the time (98.9% in Win10 and 78% in wine) is spent in SysClk_WaitTimer().

It looks like StretchBlt is a lot slower in Wine than in Windows.
Should probably check in wine mailing list if this rings a bell.

**Comment by Michaelangel007** [comment]
Thanks for providing those timings audetto !

**Comment by audetto** [comment]
From Wine there is a suggestion

https://www.winehq.org/pipermail/wine-devel/2017-April/117383.html

[HKCU\\Software\\Wine\\X11 Driver]
"ClientSideGraphics"="N" 

CPU Usage goes down 25% -> 15%

Will check what the next bottleneck is.

**Comment by rmacri** [comment]
Just chiming in that I've also noticed the CPU usage jump, 7% (1.25.0.4) to 20% (1.26.3.6) in a VMWare VM on an i7 NUC (I do all my work within VMs). I like whats happening with the emulation fidelity though, down to the principles of NTSC!
I was thinking that if in monochrome mode and no toggling of the video mode within a timeout, it could fall back to field based rendering instead of sub pixel. Have I missed something?

**Comment by tomcw** [comment]
AppleWin's full-speed mode does periodic video updates (see "Full-speed mode" in AppleWin.chm / v1.26.3.6+). This video update occurs at a wall-clock period of 16.6ms (60Hz). So perhaps a hybrid video _update_ mode of 16.6ms but for non-full-speed could be of interest?

NB. See the _Limitations_ part of the same AppleWin.chm section, as running in periodic (ie. non-cycle accurate) video update mode means that the floating bus isn't emulated, so 6502 code dependent on accurate floating bus (eg. Apple II+ video syncing) will hang. See also #519.

**Comment by audetto** [comment]
See this as well

https://github.com/AppleWin/AppleWin/issues/858

CPU usage is not as simple as interpret in linux as it is in Windows.
Currently when idle in text mode (green monitor), wine + applewin take 40% CPU.
On the same machine the linux version goes at 15% CPU with maximum FPS of 544.
In VBox same machine Windows reports < 1% CPU usage.

I find it very hard to believe that the linux version uses 15x more CPU (1% vs 15%), I suspect results are not immediately comparable.

I am happy with the current results and closing this.
