### ISSUE TITLE
Optimizing NTSC Rendering

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#401]
[Michael's NTSC optimization notes, originally posted into #399]

----

At one point I was going to post this to c.e.a2 ... but SQUIRREL.  Anyways, here are some notes from back in Jan 2015 ... IIRC most (all?) of these have been incorporated into the NTSC rendering when I cached the video mode changes byte video byte -- but it wouldn't hurt to double-check.

Enjoy! 

```
 - - - 8< - - -
```

By using DOD (Data-Orientated Design) I've managed to get a massive speed increase 2x - 4x with the NTSC rendering code via manually function unrolling. This is proof of the "Flexible & Slow" VS "Rigid & Fast" axiom.

In C++ terminology this is equivalent to "flattening virtual calls". Whoa! What is this talk about Virtual Calls? I thought Sheldon's code was all C -- he doesn't have virtual calls!? True, he doesn't have virtual function call, however, _effectively_ there are 14 function calls PER video byte! Compilers can't optimize a pointer-to-pointer-function call away.

|Calls| Function                       |
|:---:|:------------------------------:|
| x1  | wsVideoUpdate                  |
| x2  | monochrome vs chromatic branch |
| x14 | pixels                         |

This is -why- the new NTSC rendering code so slow compared to previous emulators.

**TL:DR;** Compilers can't optimize double indirection, use DOD to manual unroll.

This is an introduction to a 4 Part "whitepaper" on how Sheldon's NTSC rendering works:

# Table of Contents

  Part 0 - Legend
  Part 1 - Function call tracing
  Part 2 - Optimizing
  Part 3 - 64K lookup table

Optimzing NTSC Rendering - Part 0 - Legend
==========================================

First, some abbreviations since the original function names are little misleading.  Any time you read:

 * SinglePixel
 * DoublePixel

There are refering to _scanline blendings_, NOT pixels.
All of these actually draw *one* pixel to *two* scanlines.

The single/double refers to the type of RGB blending.

I use the terms:

```C
  half =  25%  code: mp = ((*cp & 0x00fcfcfc) >> 2)
  full = 100%  code: *mp = *cp

  half    color1 = ((color0 & 0x00fcfcfc) >> 2)
  quarter color1 = color0 - ((color2 & 0x00fcfcfc) >> 2
```

to distinguish the types of blending:

This table describes the type of scanline blending for

* Primary Scanline Brightness %, and
* Secondary Scanline Brightness %.

```
  Mode     Original Name  Description
  =========================================================
  Mon1     SINGLEPIXEL    half    100%,  25%
  Mon2     DOUBLEPIXEL    fulll   100%, 100%
  Hue1     SINGLETVPIXEL  quarter 100%,  75%
  Hue2     DOUBLETVPIXEL  fulll   100%, 100%
```

Note: Sheldon's original code has some stale code left in SINGLETVPIXEL:

```C
   prevlin = (unsigned int *)(vbp0 + 8 * FRAMEBUFFER_W); \
   prevp = *prevlin; \
```

Another problem is that unsigned, unsigned int, or long was used clouding if 16-bits or 32-bits of precision are needed. AppleWin uses the standard (stdint.h) `uint16_t` and `uint32_t` for clarity, but I digress.

```
Legend / Definitions:

  Mode     Original Name          Description
  ================================================================
  TEXT40   wsUpdateVideoText      40-col text mode
  TEXT80   wsUpdateVideoDblText   80-col text mode
  GR40     wsUpdateVideoLores     Lo-Res
  DGR40    wsUpdateVideo7MLores   Double Lo-Res w/o 80-col active
  DGR80    wsUpdateVideoDblLores  Double Lo-Res w/  80-col active
  HGR40    wsUpdateVideoHires     Hi-Res
  DHGR40   wsUpdateVideoHires0    Double Hi-Res w/o 80-col active
  DHGR80   wsUpdateVideoDblHires  Double Hi-Res w/  80-col active

           VIDEO_DRAW_BITS        'bt' is 14-bit composite signal

  B&WMon1  ntscMonoSinglePixel    Black & White Monitor: half
  B&WMon2  ntscMonoDoublePixel    Black & White Monitor: copy
  B&WTV1   ntscMonoTVSinglePixel  Black & White ColorTV: quarter
  B&WTV2   ntscMonoTVDoublePixel  Black & White ColorTV: full
  HueMon1  ntscColorSinglePixel   Chromatic     Monitor: half
  HueMon2  ntscColorDoublePixel   Chromatic     Monitor: full
  HueTV1   ntscColorTVSinglePixel Chromatic     ColorTV: quarter
  HueTV2   ntscColorTVDoublePixel Chromatic     ColorTV: mix
```

Here are the tentative cleaned up names in AppleWin 1.26

```
  Mode     Original Name                  Description
  ================================================================
  TEXT40   updateScreenText40             40-col text mode
  TEXT80   updateScreenText80             80-col text mode
  GR40     updateScreenSingleLores40      Lo-Res
  DGR40    updateScreenDoubleLores40      Double Lo-Res w/  80-col active
  DGR80    updateScreenDoubleLores80      Double Lo-Res w/o 80-col active
  HGR40    updateScreenSingleHires40      Hi-Res
  DHGR40   updateScreenDoubleHires40      Double Hi-Res w/  80-col active
  DHGR80   updateScreenDoubleHires80      Double Hi-Res w/o 80-col active

           updatePixels                   bits is 14-bit composite signal

  B&WMon1  PixelBnWMonitorSingleScanline  Black & White Monitor mode: half
  B&WMon1  PixelBnWMonitorDoubleScanline  Black & White Monitor mode: full
  B&WTV1   PixelBnWColorTVSingleScanline  Black & White ColorTV mode: quarter
  B&WTV2   PixelBnWColorTVDoubleScanline  Black & White ColorTV mode: full
  HueMon1  PixelHueMonitorSingleScanline  Chromatic     Monitor mode: half
  HueMon2  PixelHueMonitorDoubleScanline  Chromatic     Monitor mode: full
  HueTV1   PixelHueColorTVSingleScanline  Chromatic     ColorTV mode: quarter
  HueTV2   PixelHueColorTVDoubleScanline  Chromatic     ColorTV mode: full


                                             Primary Scanline Brightness %
                                                    Secondary Scanline Brightness %
  Mon1     FramebufferMonitorSingleScanline  100%,  25%
  Mon2     FramebufferMonitorDoubleScanline  100%, 100%
  Hue1     FramebufferColorTVSingleScanline  100%,  75%
  Hue2     FramebufferColorTVDoubleScanline  100%, 100%
```

Optimzing NTSC Rendering - Part 1 - Function call tracing
=========================================================

Let's trace what happens on a 6502 clock cycle

    Update Screen( # clock cycyles ) <-- first virtual function
       get 14 composite bits
          Update Pixels on 2 scanlines <-- second virtual function

Effectively there are 2 two "Virtual Functions" calls here:

   Update Screen:  wsVideoUpdate  (and corresponding wsVideoText  )
   Draw Bits    :  if color burst on, choose between monochrome or color
   Update Pixel :  ntscColorPixel (and corresponding ntscMonoPixel)

Now the first one we can't do much about, but what about inlining the second one?
Can we get rid of it?

To answer that let's take a look at the Video Mode vs Time callstack diagram:
(The video mode is across the X axis, time is across the Y axis -- `0` seconds at top, `t` seconds at bottom)

```
+--------+--------+------+------+------+-------+--------+-------+ Set : SetVideoMode( $C05x )
| TEXT40 | TEXT80 | GR40 | GR80 | GR81 | HGR40 | DHGR80 | DHGR40| Draw: updateScreenX( cycles_6502 )
+--------+--------+------+------+------+-------+--------+-------+ 
 \                                                             /
  \                                                           /
   \                                                         /
    \                                                       /
     \                                                     /
      \                                                   /
       +-------------------------------------------------+
       |                                                 | 
       |        For 14 pixels on the scanline            | 
       |Draw: VIDEO_DRAW_BITS(bt)  updatePixels(bits_14) | 
       +-------------------------------------------------+
      /                         |                         \
     /                          |                          \
    /  Black and White          |  Chromatic Hues           \
   /      ntscMonoPixel()       |     ntscColorPixel()       \
  /       g_pFuncUpdateBnWPixel |     g_pFuncUpdateHuePixel   \
 /                              |                              \
+-------+--------+------+-------|--------+--------+------+------+
|B&WMon1|B&WMon2 |B&WTV1|B&WTV2 |Monitor1|Monitor2|Color1|Color2| Set: wsVideoStyle
+-------+--------+------+-------|--------+--------+------+------+ Draw: ntsc{Mono,Color}{Single,Double}Pixel
| Mon1  | Mon2   | Hue1 | Hue2  | Mon1   | Mon2   | Hue1 | Hue 2| 
+-------+--------+------+-------|--------+--------+------+------+ 
```

Optimzing NTSC Rendering - Part 2 - Optimizations
=================================================

So how do we get our speed back?

First by analyzing the permutations:

    Video Mode  : TEXT40 / TEXT80 / GR40 / GR80 / DGR40 / HGR40 / DHGR80 / DHGR40
    Color       : Yes / No
    Display Type: Standard / TV

Since there are 3 axis we would normally need a 3D matrix.
However, we can collapse this 3D matrix down into a more readable 2D format:

```
Hue\Mode| TEXT40 | TEXT80 | GR40 | GR80 | GR81 | HGR40 | DHGR80 | DHGR40|
========+================================================================
B&WMon1 | 
B&WMon1 |
B&WTV1  |
B&WTV2  |
HueMon1 |
HueMon2 |
HueTV1  |
HueTV2  | 
```

When the user presses F9 you stay in the same column.
When a 6502 program sets video mode, you stay in the same row.

Let's say we want to optimize the HGR40 mode for Color Monitors with 100% double scanline.

Our function name is simply the Y+X names concatenated to provide an _unique_ name.

Here is an annotated example of the inner loop for: UpdateHGR40HueMon2()

```C
    //
        uint8_t *pMain = MemGetMainPtr(addr);
        uint8_t  m     = pMain[0];
        uint16_t bits  = g_aPixelDoubleMaskHGR[m & 0x7F]; // Optimization: hgrbits second 128 entries are mirror of first 128
        if (m & 0x80)
        bits = (bits << 1) | g_nLastColumnPixelNTSC;

    // Optimization #1
    // Since we KNOW the colorBurst is on
    // We don't need to waste try trying to determine if we should call
    // the monochrome or chromatic version

    // Optimization #2
    // This if( colorBurst ) switch poiNTSCColorTVnter-to-function
    // forces us to recalculate the frame buffer pointer for:
    //   a) this scanline
    //   b) the  previous scanline
    // We calculate it one 

        uint32_t  c;
        uint32_t *p = (uint32_t*)g_pVideoAddress;

    // For Mon2 only need 1 previous scanline
        uint32_t *q = p - 1*FRAMEBUFFER_W;

        g_nLastColumnPixelNTSC = (bits >> 13) & 1;
        for( int i = 0; i < 14; i++ )
        {
            g_nSignalBitsNTSC = ((g_nSignalBitsNTSC << 1) | (bits & 1)) & 0xFFF;
    // Optimization #3
    // Instead of wasting time trying to determine which table to use
    //   NTSCMono
    //   NTSCColor
    //   NTSCMonoTV
    //   NTSCColorTV
    // We already KNOW which table we'll use
        c = *((uint32_t*)&g_aHueMonitor[g_nColorPhaseNTSC][g_nSignalBitsNTSC]);

        *p = *q = c;
        bits >>= 1;

    // Optimization #4
    // There is a nextPhase table
    //   static int nextPhase[] = {1,2,3,0};
    // But this isn't needed
        ++g_nColorPhaseNTSC &= 3;

    // re-use pointer to scanlines
            p++;
            q++;
            g_pVideoAddress++;
        }
```

Optimzing NTSC Rendering - Part 3 - 64K lookup table
====================================================

Building of the 64K RGB table:

The Apple has a master clock of exactly 14,318,180 Hz, commonaly abbreviated 14 MHz.

An Apple generates a composite chroma signal at exactly: 3,579,545 Mhz. This is usually abbreviated 3.5 MHz.

Now 14 Mhz/3.5 Mhz = exactly 4 phases.

When we switch one pixel column we cycle through 1 of these 4 phases.

This means we need a:

 = 4 phases * 4096 colors * 32-bits (alpha isn't used)
 = 64K

color look-up table.

The debugger commands `ntsc save` and `ntsc load` let you import/export .BMP files that correspond to this palette.

# TODO

* [ ] Figure out how the heck `initChromaPhaseTables()` works!
  * [ ] Is it a ButterworthLowPass2 filter???
  * [ ] What are the params???
* [ ] `initFilterChroma()`
* [ ] `initFilterLuma0()`
* [ ] `initFilterLuma1()`
* [ ] `initFilterSignal()`
